import Head from 'next/head';
import FaqTabs from '@/components/FaqTab';
import QuestionTabs from '@/components/QuestionTab';
import { Sections } from '@/data/FAQ';

const DataReport = () => {
  return (
    <div>
      <Head>
        <title>Humanity Research Lab</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1.0' />

        <link rel='icon' href='/favicon.ico' />
      </Head>

      <section className='relative pt-16 pb-12 md:pt-20 md:pb-20'>
        <div className='text-center pb-12 md:pb-16 '>
          <h1
            className='mx-auto font-extrabold leading-tighter tracking-tighter mb-4'
            data-aos='zoom-y-out'
          >
            Frequently Asked Questions
          </h1>
        </div>
        <div className='text-center pb-12 md:pb-16 '>
          <FaqTabs>
          {/* ALL FAQ tab content */}
          {Sections.map((Sections) => ( 
            <div label={Sections.lable}>
            <div className='grid grid-cols-1 divide-y divide-gray-100'>
              <div className='w-full mx-6 divide-y divide-gray-500'>
                {Sections.content.map((Sections) => (
                  <QuestionTabs
                    question={Sections.question}
                    answer={Sections.answer}
                  />
                ))}
              </div>
            </div>
          </div>
          ))}
          </FaqTabs>  
        </div>
      </section>


    </div>
  );
};

export default DataReport;
