import Head from 'next/head';
import Image from 'next/image';
import { teamMembers, highlights, devInfo } from '@/data/home';

const Home = () => {
  return (
    <div>
      <Head>
        <title>Humanity Research Lab</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1.0' />

        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* Hero Section */}
      <section className='relative pt-28 pb-12 md:pt-48 md:pb-20 bg-slate-100 2333333'>
        {/* Section header */}
        {/* HRL LOGO Background */}
        <div
          className='absolute inset-0 scale-150 filter opacity-40 bg-hrl rotate-12 pointer-events-none 2333333'
          aria-hidden='true'
        ></div>
        <div className='text-center pb-12 md:pb-16 '>
          <h1
            className='text-5xl mx-auto md:text-6xl font-extrabold leading-tighter tracking-tighter mb-4'
            data-aos='zoom-y-out'
          >
            History beyond{' '}
            <span className='text-gradient-hrl'>New York City</span>
          </h1>
          <div className='max-w-3xl mx-auto'>
            <p
              className='text-xl text-gray-600 mb-8'
              data-aos='zoom-y-out'
              data-aos-delay='150'
            >
              History Beyond gives undergraduate students experiences in
              undertaking independent historical research. The course encourages
              students to think creatively and boldly, to negotiate past
              difficulties in collaboration, and to learn from setbacks.
            </p>
            <div
              className='max-w-xs mx-auto sm:max-w-none sm:flex sm:justify-center'
              data-aos='zoom-y-out'
              data-aos-delay='300'
            >
              <div>
                <a
                  className='btn text-white bg-accent hover:bg-accent-darker w-full sm:w-auto sm:ml-4 shadow-sm'
                  href='#0'
                >
                  Learn more
                </a>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* What is HRL */}
      <section className='relative px-8 pb-12 md:pt-2 md:pb-20 bg-gray-100 2333333'>
        {/* Section background (needs .relative class on parent and next sibling elements) */}
        {/* <div
          className='absolute inset-0 bg-gray-300 pointer-events-none 2333333'
          aria-hidden='true'
        ></div> */}
        <div className='absolute left-0 right-0 m-auto w-px p-px h-20 bg-gray-200 transform -translate-y-1/2'></div>

        <div className='relative max-w-6xl mx-auto px-4 sm:px-6'>
          <div className='pt-12 md:pt-20'>
            {/* Section header */}
            <div className='max-w-3xl mx-auto text-center pb-6 md:pb-12'>
              <h2 className='mb-4'>
                What is <span className='text-gradient-hrl'>HRL</span>
              </h2>
              <p className='text-xl text-gray-600'>
                A class at{' '}
                <a
                  href='https://shanghai.nyu.edu/'
                  className=' underline text-gradient-nyush font-bold'
                >
                  NYU Shanghai
                </a>
              </p>
            </div>

            {/* Section content */}
            <div className='md:grid md:grid-cols-12 md:gap-6'>
              {/* Content */}
              <div
                className='max-w-xl md:max-w-none md:w-full mx-auto md:col-span-6 md:mt-6'
                data-aos='fade-right'
              >
                <div className='md:pr-4 lg:pr-12 xl:pr-16 mb-8'>
                  <div className='w-full aspect-w-16 aspect-h-12 rounded-3xl shadow-lg bg-teal-900 mb-4'></div>
                  <h3 className='mb-3'>Title 1</h3>
                  <p className='md:text-xl text-gray-600'>
                    Duis aute irure dolor in reprehenderit in voluptate velit
                    esse cillum dolore pariatur. Excepteur sint occaecat
                    cupidatat non proident, sunt in culpa.
                  </p>
                </div>
              </div>
              <div
                className='max-w-xl md:max-w-none md:w-full mx-auto md:col-span-6 md:mt-6'
                data-aos='fade-left'
              >
                <div className='md:pr-4 lg:pr-12 xl:pr-16 mb-8'>
                  <div className='w-full aspect-w-16 aspect-h-12 rounded-3xl shadow-lg bg-teal-900 mb-4'></div>

                  <h3 className='mb-3'>Title 2</h3>
                  <p className='md:text-xl text-gray-600'>
                    Duis aute irure dolor in reprehenderit in voluptate velit
                    esse cillum dolore pariatur. Excepteur sint occaecat
                    cupidatat non proident, sunt in culpa.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Course & Highlights */}
      <section className='px-8 pb-12 md:pt-2 md:pb-20 bg-slate-100 2333333'>
        {/* Section background (needs .relative class on parent and next sibling elements) */}
        {/* <div
          className='absolute inset-0 bg-gray-300 pointer-events-none 2333333'
          aria-hidden='true'
        ></div> */}
        <div className='absolute left-0 right-0 m-auto w-px p-px h-20 bg-gray-200 transform -translate-y-1/2'></div>

        <div className='relative max-w-6xl mx-auto px-4 sm:px-6'>
          <div className='pt-12 md:pt-20'>
            {/* Section header */}
            <div className='max-w-3xl mx-auto text-center pb-6 md:pb-12'>
              <h2 className='mb-4'>Course & Highlights</h2>
            </div>

            {/* Section content */}
            <div className='md:grid md:grid-cols-12 md:gap-6'>
              {/* Content */}

              {highlights.map((highlight) => (
                <div
                  key={highlight.title}
                  className='max-w-xl md:max-w-none md:w-full mx-auto md:col-span-4 md:mt-6'
                  data-aos='fade-right'
                >
                  <div className='md:pr-4 lg:pr-12 xl:pr-16 mb-8'>
                    <div className='w-full max-w-2xl aspect-w-16 aspect-h-12  mb-4'>
                      <Image
                        src={highlight.image}
                        alt={highlight.title}
                        layout={'fill'}
                        className='rounded-3xl object-cover'
                      />
                    </div>
                    <h4 className='mb-3'>{highlight.title}</h4>
                    <p className='md:text-xl text-gray-600'>
                      {highlight.description}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Development & Information */}
      <section className='px-8 pb-12 md:pt-2 md:pb-20 bg-gray-100 2333333'>
        {/* Section background (needs .relative class on parent and next sibling elements) */}
        {/* <div
          className='absolute inset-0 bg-gray-300 pointer-events-none 2333333'
          aria-hidden='true'
        ></div> */}
        <div className='absolute left-0 right-0 m-auto w-px p-px h-20 bg-gray-200 transform -translate-y-1/2'></div>

        <div className='relative max-w-6xl mx-auto px-4 sm:px-6'>
          <div className='pt-12 md:pt-20'>
            {/* Section header */}
            <div className='max-w-3xl mx-auto text-center pb-6 md:pb-12'>
              <h2 className='mb-4'> Development & Information</h2>
            </div>

            {/* Section content */}
            <div className='md:grid md:grid-cols-10 md:gap-6 justify-center items-center'>
              {/* Content */}
              {devInfo.map((devInfo, key) => (
                <div
                  key={key}
                  className='max-w-xl md:max-w-none md:w-full mx-auto md:col-span-2 md:mt-6'
                  data-aos='fade-down'
                >
                  <div className='md:px-2 lg:px-6 xl:px-8 mb-8 text-center'>
                    <div className='aspect-w-1 aspect-h-1 object-cover m-auto '>
                      <Image
                        src={devInfo.image}
                        alt={devInfo.title}
                        layout={'fill'}
                        className='rounded-full object-cover'
                      />
                    </div>

                    <h4 className='md:text-xl text-gray-600 font-normal'>
                      {devInfo.number}
                    </h4>
                    <h4 className='mb-3'>{devInfo.title}</h4>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Team Members */}
      <section className='px-8 pb-12 md:pt-2 md:pb-20 bg-slate-100 2333333'>
        {/* Section background (needs .relative class on parent and next sibling elements) */}
        {/* <div
          className='absolute inset-0 bg-gray-300 pointer-events-none 2333333'
          aria-hidden='true'
        ></div> */}
        <div className='absolute left-0 right-0 m-auto w-px p-px h-20 bg-gray-200 transform -translate-y-1/2'></div>

        <div className='relative max-w-6xl mx-auto px-4 sm:px-6'>
          <div className='pt-12 md:pt-20'>
            {/* Section header */}
            <div className='max-w-3xl mx-auto text-center pb-6 md:pb-12'>
              <h2 className='mb-4'> Team Members</h2>
            </div>

            {/* Section content */}
            <div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8'>
              {/* Content */}
              {teamMembers.map((teamMember, key) => (
                <div
                  key={key}
                  className='w-full md:max-w-none md:w-full mx-auto md:col-span-1 md:mt-6'
                  data-aos='fade-down'
                >
                  <div className='md:px-2 lg:px-6 xl:px-8 mb-8 text-center'>
                    <div className='aspect-w-1 aspect-h-1 object-cover m-auto mb-3'>
                      <Image
                        src={teamMember.image}
                        alt={teamMember.name}
                        layout={'fill'}
                        className='rounded-full object-cover'
                      />
                    </div>

                    <h4 className=''>{teamMember.name}</h4>
                    <p className='md:text-xl text-gray-600 mb-3'>
                      {teamMember.title}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Home;
